### ISSUE TITLE
Se necesita crear un nuevo campo

### ISSUE THREAD

**Issue by faraday58** [faraday58/ejemplo-clase-git#1]
https://github.com/faraday58/ejemplo-clase-git/blob/c86d414d4cc205b34fcb77db79882382dd625b94/Persona.java#L1
En la clase persona requerimos crear el campo teléfono

**Comment by Ramon1111** [comment]
Claro!
ya lo agregué

**Comment by faraday58** [comment]
Sí ya quedó y se ejecuta correctamente
