### ISSUE TITLE
Código Main no tiene nada :(

### ISSUE THREAD

**Issue by TonatiuhCruz9** [faraday58/ejemplo-clase-git#2]
https://github.com/faraday58/ejemplo-clase-git/blob/c86d414d4cc205b34fcb77db79882382dd625b94/MainActivity.java#L1

**Comment by faraday58** [comment]
Sí, esta parte necesita el código de entrada

**Comment by Ramon1111** [comment]
Confirmo, no tiene nada :c

**Comment by TonatiuhCruz9** [comment]
Sigue igual :(

**Comment by Ramon1111** [comment]
Sigue igual ;A;

**Comment by faraday58** [comment]
Verifiquen en la rama login: https://github.com/faraday58/ejemplo-clase-git/blob/login/MainActivity.java#L3
